services:
  - type: web
    name: id-document-extractor
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && pip install -r web_app/requirements.txt"
    startCommand: "gunicorn --chdir web_app app:app"
    envVars:
      - key: GEMINI_API_KEY
        fromSecret: true